[default]
SECRET_KEY = '\xfd{H\xe5<\x95\xf9\xe3\x96.5\xd1\x01O<!\xd5\xa2\xa0\x9fR"\xa1\xa8'
SQLALCHEMY_DATABASE_URI = 'postgresql://docker:xlsolution@database/xlsolution'
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    'app.resources:init_app',
    'app.db:init_app'
]