USE [master]
GO

/****** Object:  Database [projetoxl]    Script Date: 26/02/2018 11:49:53 ******/
CREATE DATABASE [projetoxl]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'projetoxl', FILENAME = N'c:\databases\projetoxl\projetoxl.mdf' , SIZE = 3264KB , MAXSIZE = 20971520KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'projetoxl_log', FILENAME = N'c:\databases\projetoxl\projetoxl_log.ldf' , SIZE = 69760KB , MAXSIZE = 1048576KB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [projetoxl].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [projetoxl] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [projetoxl] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [projetoxl] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [projetoxl] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [projetoxl] SET ARITHABORT OFF 
GO

ALTER DATABASE [projetoxl] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [projetoxl] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [projetoxl] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [projetoxl] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [projetoxl] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [projetoxl] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [projetoxl] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [projetoxl] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [projetoxl] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [projetoxl] SET  DISABLE_BROKER 
GO

ALTER DATABASE [projetoxl] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [projetoxl] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [projetoxl] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [projetoxl] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [projetoxl] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [projetoxl] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [projetoxl] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [projetoxl] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [projetoxl] SET  MULTI_USER 
GO

ALTER DATABASE [projetoxl] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [projetoxl] SET DB_CHAINING OFF 
GO

ALTER DATABASE [projetoxl] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [projetoxl] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [projetoxl] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [projetoxl] SET  READ_WRITE 
GO


