// Stocks
export const GET_QUOTE = 'GET_QUOTE';
export const GET_QUOTE_SUCCESS = 'GET_QUOTE_SUCCESS';

export const GET_HISTORY = 'GET_HISTORY';
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';

export const REQUEST_COMPARE_STOCKS = 'REQUEST_COMPARE_STOCKS';
export const REQUEST_COMPARE_STOCKS_SUCCESS = 'REQUEST_COMPARE_STOCKS_SUCCESS';

export const GET_GAINS = 'GET_GAINS';
export const GET_GAINS_SUCCESS = 'GET_GAINS_SUCCESS';

export const ADD_PORTFOLIO = 'ADD_PORTFOLIO';
export const CLEAR_COMPARE = 'CLEAR_COMPARE';
export const REMOVE_PORTFOLIO = 'REMOVE_PORTFOLIO';
