# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XL_APP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!



  # Pods for XL_APP
  pod 'SQLite.swift', '~> 0.11.4'

end
