CREATE PROCEDURE sp_ObterProdutos   
as    
    
begin      
 SELECT MF.CODMODELO, MF.DESCRICAO as MODELO, E.COR, F.CODFABRICANTE, F.NOME as FABRICANTE,    
  E.PRECO as VALOR, E.QUANTIDADE, E.PLANOVENDA    
 FROM MODELOFABRICANTE MF JOIN FABRICANTE F ON F.CODFABRICANTE = MF.CODFABRICANTE    
  JOIN ESTOQUE E ON E.CODMODELO = MF.CODMODELO;    
end;

CREATE PROCEDURE sp_ObterProdutosPorFabricante  
    @Fabricante nvarchar(100)    
as        
begin    
    
SELECT MF.CODMODELO, F.CODFABRICANTE, MF.DESCRICAO as MODELO, E.COR, F.NOME as FABRICANTE,    
  E.PRECO as VALOR, E.QUANTIDADE, E.PLANOVENDA    
 FROM MODELOFABRICANTE MF JOIN FABRICANTE F ON F.CODFABRICANTE = MF.CODFABRICANTE    
  JOIN ESTOQUE E ON E.CODMODELO = MF.CODMODELO   
WHERE F.NOME LIKE '%' + UPPER(@Fabricante) + '%';    
end;

CREATE PROCEDURE sp_ObterProdutosPorModelo  
    @Modelo nvarchar(100)    
as    
    
begin      
 SELECT MF.CODMODELO, F.CODFABRICANTE, MF.DESCRICAO as MODELO, E.COR, F.NOME as FABRICANTE,    
  E.PRECO as VALOR, E.QUANTIDADE, E.PLANOVENDA    
 FROM MODELOFABRICANTE MF JOIN FABRICANTE F ON F.CODFABRICANTE = MF.CODFABRICANTE    
  JOIN ESTOQUE E ON E.CODMODELO = MF.CODMODELO     
 WHERE MF.DESCRICAO LIKE '%' + UPPER(@Modelo) + '%';    
end;

CREATE PROCEDURE sp_ObterProdutosPorTipoVenda  
    @TipoVenda nvarchar(100)    
as    
    
begin      
 SELECT MF.CODMODELO, F.CODFABRICANTE, MF.DESCRICAO as MODELO, E.COR, F.NOME as FABRICANTE,    
  E.PRECO as VALOR, E.QUANTIDADE, E.PLANOVENDA    
 FROM MODELOFABRICANTE MF JOIN FABRICANTE F ON F.CODFABRICANTE = MF.CODFABRICANTE    
  JOIN ESTOQUE E ON E.CODMODELO = MF.CODMODELO     
 WHERE E.PLANOVENDA LIKE '%' + UPPER(@TipoVenda) + '%';    
end;